version: '3.4'

services:
  mainvacancybot:
    image: mainvacancybot
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 env/lib64/python3.8/site-packages/dotenv/main.py "]
    ports:
      - 5678:5678
